# Libreria numpy

In [2]:
import numpy as np

In [3]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#Numero de dimenciones que tiene el arreglo
array.ndim

2

In [15]:
#El primer valor que se mostrara seran las filas y las columnas
array.shape

(3, 3)

In [16]:
#Numero de posiciones que tiene el arreglo
array.size

9

In [17]:
#Muestra el tipo de valore que contiene el arreglo
array.dtype.name

'int32'

## Operaciones matematicas

In [25]:
#Suma de dos arreglos, considera que deben ser de las mismas dimenciones
#Lo mismo aplica para cualquier otra operacion basica.
array_a=np.array([1,1,1,1])
array_b=np.array([2,2,2,2])
a+b

array([3, 3, 3, 3])

In [26]:
#Elevar al cuadrado un arreglo
array_b**2

array([4, 4, 4, 4], dtype=int32)

In [27]:
#Elevar al cuadrado un arreglo
np.square(array_b)

array([4, 4, 4, 4], dtype=int32)

In [32]:
#Funciones trigonometricas (sin,cos,tan)
np.tan(array_b)

array([-2.18503986, -2.18503986, -2.18503986, -2.18503986])

In [33]:
#Operaciones condicionales (retornar true o false para cada una de las posiciones)
array_b>array_a

array([ True,  True,  True,  True])

In [34]:
#Multiplicacion de matrices
M1 = np.array([[1,2],[0,1]])
M2 = np.array([[-1,0],[1,1]])
M1*M2

array([[-1,  0],
       [ 0,  1]])

In [36]:
#Se obtiene el producto
np.dot(M1,M2)

array([[1, 2],
       [1, 1]])

In [39]:
#Valores nulos (np.nan)
arr = np.array([1.5, 0.8, np.nan, 3.5,np.nan,np.nan])
arr

array([1.5, 0.8, nan, 3.5, nan, nan])

In [40]:
#Sustituir valores nulos dentro de un arreglo en este caso por  0
arr[np.isnan(arr)] = 0
arr

array([1.5, 0.8, 0. , 3.5, 0. , 0. ])

In [41]:
#Lista 
list = [1,3,-0.5,7,-3,15.4,8.2,7.5]

In [42]:
#Transformar una lista en un arreglo
array=np.array(list)
array

array([ 1. ,  3. , -0.5,  7. , -3. , 15.4,  8.2,  7.5])

In [43]:
print('Mean:', array.mean())
print('Median:', np.median(array))
print('Range (Max-Min):', np.ptp(array))
print('Standard deviation:', array.std())
print('80th percentile:', np.percentile(array, 80))
print('0.3-quantile:', np.quantile(array, 0.3))

Mean: 4.825
Median: 5.0
Range (Max-Min): 18.4
Standard deviation: 5.507438152172024
80th percentile: 7.92
0.3-quantile: 1.2000000000000002


In [50]:
array.mean(),np.median(array),np.ptp(array),array.std(),np.percentile(array, 80),np.quantile(array, 0.3)

(4.825, 5.0, 18.4, 5.507438152172024, 7.92, 1.2000000000000002)

In [52]:
#Busqueda de posiciones dentro de un arreglo
a = np.array([[3,4,5],[7,8,3],[0,3,23],[8,11,6]])
a[1][1]

8

In [53]:
#visualizamos el arreglo denominado como "a"
a

array([[ 3,  4,  5],
       [ 7,  8,  3],
       [ 0,  3, 23],
       [ 8, 11,  6]])

In [54]:
#Busca en la fila 0 y columna 0 los primeros dos valores(no hablamos de posiciones)
a[0,0:2]

array([3, 4])

In [55]:
#Obtiene la informacion de toda las columnas de la fila seleccionada
a[0,:]

array([3, 4, 5])

In [60]:
#Obtiene todas las filas de la columa seleccionada
a[:,1]

array([ 4,  8,  3, 11])

In [61]:
#Obtiene todas las filas de la ultima columna
a[:,-1]

array([ 5,  3, 23,  6])

## Manipulacion de dimenciones

In [62]:
#Transforma un arreglo bidimencional a unidimencional
a.ravel()

array([ 3,  4,  5,  7,  8,  3,  0,  3, 23,  8, 11,  6])

In [69]:
#Cambia un arreglo unidimencional a bidimencional especificando filas y culumnas
a.shape=(4,3)
a

array([[ 3,  4,  5],
       [ 7,  8,  3],
       [ 0,  3, 23],
       [ 8, 11,  6]])

In [75]:
#Transpuesta de una matriz(cambia la matriz de vertical a horizontal)
a.transpose()

array([[ 3,  7,  0,  8],
       [ 4,  8,  3, 11],
       [ 5,  3, 23,  6]])

In [78]:
#Generar data en un intervalo determinado, de -1 a 1 y la cantidad de valores
c = np.linspace(-1,1,20)
c

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [79]:
# NEW AXIS , Cantidad de valores en un arreglo unidimencional
x1 = np.array([1, 2, 3, 4, 5])
x1.shape

(5,)

In [82]:
#Agrega una nueva dimencion al arreglo en este caso las columnas
x1_new = x1[:, np.newaxis]
x1_new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [85]:
#Ver la dimencion del la nueva matriz generada a partir del arreglo "x1"
x1_new.shape

(5, 1)

In [87]:
#Suma cada uno de los valores del arreglo a cada uno de los valores de la matriz
x2=np.array([6,7,8])
x3=x1_new+x2
x3

array([[ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13]])

In [92]:
#Creamos un nuevo arreglo al cual le asignamos los valores de la columa 0 de "x3" en dos dimenciones
x3_new = x3[:,np.newaxis,0]
x3_new

array([[ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [93]:
#Creamos un nuevo arreglo al cual le asignamos los valores de la columa 0 de "x3" en unna sola dimencion
x3_new_ = x3[:,0]
x3_new_

array([ 7,  8,  9, 10, 11])

In [95]:
# Squeeze
#El numero de corchetes define la cantidad dimenciones con las que se estan trabajando
arr = np.array([[[2, 2, 2], [2, 2, 2]]])   
print(arr)
print("Shape of input array : ", arr.shape)

[[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)


In [96]:
#Elimina una dimencion y se queda con solo filas y columnas
arr_ = np.squeeze(arr)  
print(arr_)
print("Shape of output array : ", arr_.shape) 

[[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


## Reference:
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

https://docs.scipy.org